### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by mosu001** [tumi8/vermont#23]
I have downloaded vermont from git, configured it and am now trying to make it

cd vermont
cmake -DSUPPORT_SCTP=OFF -DSUPPORT_REDIS=ON -DWITH_TOOLS=OFF
make

I get error that IPFIX_TYPEID_mplsLabelStackEntry1 and IPFIX_TYPEID_mplsLabelStackEntry10 are not defined on lines 159 and 160 of IpfixFlowInspectorExporter.cpp. I grepped the src directories and these terms only appear (also undefined) in IpfixDBWriterMongo.cpp. Please help as I am trying to get Flow Inspector going and having no luck! See attached files for the compile error and grep output.

![vermont-compile-error](https://cloud.githubusercontent.com/assets/9683473/5001399/25ba6f60-6a5a-11e4-8347-07e70b6b256c.png)
![vermont-grep-output](https://cloud.githubusercontent.com/assets/9683473/5001398/25b5908a-6a5a-11e4-803a-8c5de6e5b191.png)

**Comment by nickbroon** [comment]
I guess this has been fixed by #47 and can be closed?
