### ISSUE TITLE
About ipfixPrinter, How can i specify the columns?

### ISSUE THREAD

**Issue by zyanbingchn** [tumi8/vermont#25]
Now, it output the default columns:
srcip,dstip,srcport,dstport,prot,srcpkts,dstpkts,srcoct,dstoct,srcstart,srcend,dststart,dstend,srcplen,dstplen,forcedexp,revstart,flowcnt,tranoct,revtranoct

**Comment by ogasser** [comment]
You specify the configuration in the XML file. Can you describe your issue in more detail please?

**Comment by zyanbingchn** [comment]
I used the ipfixPrinter to output ipfix record to txt file, but I can not explicitly specify the output columns. for example, I want it only output the 4 column:  srcip, dstip, srcport, dstport.
thank u !

<ipfixPrinter id="8">
		<outputType>table</outputType>
		<filename>ipfixResult.txt</filename>
</ipfixPrinter>

**Comment by ogasser** [comment]
You can try to use the IpfixAggregator moduel [1] to achive this.

[1] https://github.com/tumi8/vermont/wiki/Moduleconfiguration#ipfixaggregator

**Comment by zyanbingchn** [comment]
IpfixAggregator can not achive my goal.

The output column of ipfixPrinter has been writen in the code!!!

Please see below code:
it is in file: IpfixPrinter.cpp

****************************************************************
IpfixPrinter::IpfixPrinter
  if (outputtype==TABLE)
		fprintf(fh, "srcip\tdstip\tsrcport\tdstport\tprot\tsrcpkts\tdstpkts\tsrcoct\tdstoct\tsrcstart\tsrcend\n");

****************************************************************
void IpfixPrinter::printTableRecord(IpfixDataRecord* record)
{
	Connection c(record);

	//fprintf(fh, "%llu\t%llu\t%u\t%u\t%llu\n", ntohll(c.srcOctets), ntohll(c.srcPackets), c.srcPayloadLen, c.srcPayloadPktCount, c.srcTimeEnd-c.srcTimeStart);
	fprintf(fh, "%s\t%s\t%hu\t%hu\t%hhu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%u\t%u\t%hhu\t%hhu\t%u\t%llu\t%llu\n",
			IPToString(c.srcIP).c_str(), IPToString(c.dstIP).c_str(), ntohs(c.srcPort), ntohs(c.dstPort), c.protocol,
			(long long unsigned)ntohll(c.srcPackets), (long long unsigned)ntohll(c.dstPackets), (long long unsigned)ntohll(c.srcOctets), (long long unsigned)ntohll(c.dstOctets),
			(long long unsigned)c.srcTimeStart, (long long unsigned)c.srcTimeEnd, (long long unsigned)c.dstTimeStart, (long long unsigned)c.dstTimeEnd,
			c.srcPayloadLen, c.dstPayloadLen, c.dpaForcedExport, c.dpaReverseStart, c.dpaFlowCount, (long long unsigned)c.srcTransOctets, (long long unsigned)c.dstTransOctets);

}

**Comment by ogasser** [comment]
Ah yes, correct!
So you have two options:
1. Pipe the output to `awk`, `cut` or an equivalent tool to extract only the information relevant to you
2. Change the code and recompile

**Comment by zyanbingchn** [comment]
The problem is, the count of ipfix fields is about 400 num, but the Connection class has only twenty more fields.
My requirement is output more ipfix fields, which the Connection class has not.

**Comment by ogasser** [comment]
Ok, I see two options again:

1. Modify the Vermont code to add more fields and then output those.
2. Store the flow data in a database and create another script which periodically reads it out of the database and displays it.

**Comment by zyanbingchn** [comment]
Ok, Let me research it.

Thank you very much!

**Comment by zyanbingchn** [comment]
Hi, ogasser! How do you do!

About the problem which we discussed above, I find the ipfixDBWriter module which supports specifying the output columns:

<ipfixDbWriter id="10">
    <dbType>mysql</dbType>
    <host>127.0.0.1</host>
    <port>3306</port>
    <dbname>flows</dbname>
    <username>vermont</username>
    <password>v_password</password>
    <bufferrecords>30</bufferrecords>
    <tablePrefix>f</tablePrefix>
    <columns>
        <name>flowStartSeconds</name>
        <name>flowEndSeconds</name>
        <name>sourceIPv4Address</name>
        <name>destinationIPv4Address</name>
        <name>octetDeltaCount</name>
        <name>packetDeltaCount</name>
    </columns>
</ipfixDbWriter>


So, I modify the source code of ipfixDbWriter module, let it output the specified column values directly to file or port, not database. ( I deleted the code about database process.)
Now, it can fill my original requirement on the whole.

But, unfortunately, the packetAggregator module can only support about 30 ipfix columns, thus we can only get these about 30 ipfix column results.
Why the vermont did not support all ipfix columns? 

Note: the previous module of ipfixDbWriter is packetAggregator.

**Comment by ogasser** [comment]
What is the error message you get, when you specify more than 30 columns in the packet aggregator module?

**Comment by zyanbingchn** [comment]
Oh, you are misapprehensive.  It did not limitted the max count of columns.

My meaning is that it supports only part of the ipfix columns, the count of these columns is about 30.

please refer the code:

IeInfo::getValidProtocols()
PacketHashtable::typeAvailable
PacketHashtable::isRawPacketPtrVariable
PacketHashtable::getRawPacketFieldOffset
...
...

if you specify a column which did not support, it would throw exception.
