### ISSUE TITLE
Requires openssl/ssl.h despite SUPPORT_DTLS=OFF

### ISSUE THREAD

**Issue by benerudolph** [tumi8/vermont#85]
while building vermont master@a1565d8 i got the following error:
```In file included from /tmp/vermont/src/modules/ipfix/IpfixExporterCfg.cpp:21:0:
/tmp/vermont/src/common/ipfixlolib/ipfixlolib_dtls.h:5:25: fatal error: openssl/ssl.h: Datei oder Verzeichnis nicht gefunden
 #include <openssl/ssl.h>
```

I used configure to set SUPPORT_DTLS=OFF and I do not have libssl-dev installed. I know this causes the error however I think openssl headers should only be required when configured this way.
Maybe related to #64, #83. Maybe this is already fixed in some of the new feature branches.

**Comment by nickbroon** [comment]
```
In file included from vermont/src/modules/ipfix/IpfixExporterCfg.cpp:21:0:
vermont/src/common/ipfixlolib/ipfixlolib_dtls.h:5:10: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
src/modules/CMakeFiles/modules.dir/build.make:1502: recipe for target 'src/modules/CMakeFiles/modules.dir/ipfix/IpfixExporterCfg.cpp.o' failed
make[2]: *** [src/modules/CMakeFiles/modules.dir/ipfix/IpfixExporterCfg.cpp.o] Error 1
```

It looks like IpfixExporterCfg.cpp needs to conditionally on `#ifdef SUPPORT_DTLS` include ipfixlolib_dtls.h

**Comment by nickbroon** [comment]
I should have PR open to fix this very shortly.

**Comment by benerudolph** [comment]
Much appreciated. Hence I have no deeper knowledge of the sources and where openssh functions are called I thought it would be better to have someone with more knowledge to work on this.
